/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pendidikan: Pendidikan;
    riwayat: Riwayat;
    riset: Riset;
    publikasi: Publikasi;
    mengajar: Mengajar;
    kegiatan: Kegiatan;
    'tema-roadmap': TemaRoadmap;
    roadmap: Roadmap;
    media: Media;
    users: User;
    'log-sinkron': LogSinkron;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pendidikan: PendidikanSelect<false> | PendidikanSelect<true>;
    riwayat: RiwayatSelect<false> | RiwayatSelect<true>;
    riset: RisetSelect<false> | RisetSelect<true>;
    publikasi: PublikasiSelect<false> | PublikasiSelect<true>;
    mengajar: MengajarSelect<false> | MengajarSelect<true>;
    kegiatan: KegiatanSelect<false> | KegiatanSelect<true>;
    'tema-roadmap': TemaRoadmapSelect<false> | TemaRoadmapSelect<true>;
    roadmap: RoadmapSelect<false> | RoadmapSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'log-sinkron': LogSinkronSelect<false> | LogSinkronSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    profil: Profil;
    metrik: Metrik;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    profil: ProfilSelect<false> | ProfilSelect<true>;
    metrik: MetrikSelect<false> | MetrikSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sinkronMingguan: TaskSinkronMingguan;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pendidikan".
 */
export interface Pendidikan {
  id: number;
  jenjang: 'S1' | 'S2' | 'S3' | 'Profesi' | 'Lainnya';
  tahunMasuk?: number | null;
  tahunLulus: number;
  perguruanTinggi: string;
  programStudi?: string | null;
  /**
   * Contoh: Doctor of Engineering
   */
  gelar?: string | null;
  negara?: string | null;
  /**
   * URL asal data
   */
  sumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "riwayat".
 */
export interface Riwayat {
  id: number;
  nama: string;
  jenis: 'jabatan' | 'organisasi' | 'penghargaan' | 'pelatihan';
  /**
   * Contoh: 2020–2024 atau 2018–sekarang
   */
  periode?: string | null;
  /**
   * Untuk urutan
   */
  tahunMulai?: number | null;
  sumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "riset".
 */
export interface Riset {
  id: number;
  judul: string;
  jenis: 'penelitian' | 'pengabdian';
  tahun: number;
  peran?: ('ketua' | 'anggota') | null;
  ketua?: string | null;
  /**
   * Pisahkan dengan koma
   */
  anggota?: string | null;
  skema?: string | null;
  /**
   * Rupiah, tanpa titik
   */
  dana?: number | null;
  sumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Terisi otomatis dari Google Scholar dan SINTA lewat tombol sinkron di menu Metrik. Entri yang diedit manual tidak ditimpa, kecuali angka sitasi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publikasi".
 */
export interface Publikasi {
  id: number;
  judul: string;
  tahun?: number | null;
  indeks?: ('scopus' | 'wos' | 'garuda' | 'scholar' | 'pddikti')[] | null;
  venue?: string | null;
  penulis?: string | null;
  /**
   * Contoh: Q2
   */
  kuartil?: string | null;
  /**
   * Contoh: Sinta 2
   */
  akreditasi?: string | null;
  doi?: string | null;
  tautan?: string | null;
  sitasiScholar?: number | null;
  sitasiScopus?: number | null;
  /**
   * Tidak tampil di website
   */
  sembunyikan?: boolean | null;
  /**
   * Kemungkinan milik penulis lain
   */
  perluVerifikasi?: boolean | null;
  /**
   * Sinkron tidak menimpa judul, venue, dan penulis
   */
  diubahManual?: boolean | null;
  catatan?: string | null;
  sumber?: string | null;
  kunci?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mengajar".
 */
export interface Mengajar {
  id: number;
  mataKuliah: string;
  /**
   * Format PDDikti, contoh: 2025/2026 Genap
   */
  semester: string;
  kode?: string | null;
  kelas?: string | null;
  perguruanTinggi?: string | null;
  sumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kegiatan".
 */
export interface Kegiatan {
  id: number;
  judul: string;
  tanggal: string;
  tempat?: string | null;
  ringkasan?: string | null;
  gambar?: (number | null) | Media;
  /**
   * Tautan berita asli
   */
  sumber?: string | null;
  tampil?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tema-roadmap".
 */
export interface TemaRoadmap {
  id: number;
  nama: string;
  warna: 'hijau' | 'amber' | 'biru' | 'bata';
  urutan?: number | null;
  /**
   * Satu sampai dua kalimat untuk bagian Fokus riset
   */
  deskripsi?: string | null;
  /**
   * Pisahkan dengan koma. Publikasi yang judulnya memuat kata ini tampil sebagai karya tema.
   */
  kataKunci?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tiap titik menjadi cabang tinta di website. Tandai "Rencana" untuk riset ke depan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap".
 */
export interface Roadmap {
  id: number;
  judul: string;
  tahun: number;
  tema?: (number | null) | TemaRoadmap;
  /**
   * Contoh: Publikasi Scopus Q2
   */
  jenis?: string | null;
  /**
   * Contoh: DIPA BLU FMIPA
   */
  keterangan?: string | null;
  /**
   * Riset yang belum berjalan
   */
  rencana?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "log-sinkron".
 */
export interface LogSinkron {
  id: number;
  sumber: 'scholar' | 'sinta';
  status: 'berhasil' | 'gagal';
  ringkasan?: string | null;
  ditambahkan?: number | null;
  diperbarui?: number | null;
  pesan?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sinkronMingguan';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sinkronMingguan') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pendidikan';
        value: number | Pendidikan;
      } | null)
    | ({
        relationTo: 'riwayat';
        value: number | Riwayat;
      } | null)
    | ({
        relationTo: 'riset';
        value: number | Riset;
      } | null)
    | ({
        relationTo: 'publikasi';
        value: number | Publikasi;
      } | null)
    | ({
        relationTo: 'mengajar';
        value: number | Mengajar;
      } | null)
    | ({
        relationTo: 'kegiatan';
        value: number | Kegiatan;
      } | null)
    | ({
        relationTo: 'tema-roadmap';
        value: number | TemaRoadmap;
      } | null)
    | ({
        relationTo: 'roadmap';
        value: number | Roadmap;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'log-sinkron';
        value: number | LogSinkron;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pendidikan_select".
 */
export interface PendidikanSelect<T extends boolean = true> {
  jenjang?: T;
  tahunMasuk?: T;
  tahunLulus?: T;
  perguruanTinggi?: T;
  programStudi?: T;
  gelar?: T;
  negara?: T;
  sumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "riwayat_select".
 */
export interface RiwayatSelect<T extends boolean = true> {
  nama?: T;
  jenis?: T;
  periode?: T;
  tahunMulai?: T;
  sumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "riset_select".
 */
export interface RisetSelect<T extends boolean = true> {
  judul?: T;
  jenis?: T;
  tahun?: T;
  peran?: T;
  ketua?: T;
  anggota?: T;
  skema?: T;
  dana?: T;
  sumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publikasi_select".
 */
export interface PublikasiSelect<T extends boolean = true> {
  judul?: T;
  tahun?: T;
  indeks?: T;
  venue?: T;
  penulis?: T;
  kuartil?: T;
  akreditasi?: T;
  doi?: T;
  tautan?: T;
  sitasiScholar?: T;
  sitasiScopus?: T;
  sembunyikan?: T;
  perluVerifikasi?: T;
  diubahManual?: T;
  catatan?: T;
  sumber?: T;
  kunci?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mengajar_select".
 */
export interface MengajarSelect<T extends boolean = true> {
  mataKuliah?: T;
  semester?: T;
  kode?: T;
  kelas?: T;
  perguruanTinggi?: T;
  sumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kegiatan_select".
 */
export interface KegiatanSelect<T extends boolean = true> {
  judul?: T;
  tanggal?: T;
  tempat?: T;
  ringkasan?: T;
  gambar?: T;
  sumber?: T;
  tampil?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tema-roadmap_select".
 */
export interface TemaRoadmapSelect<T extends boolean = true> {
  nama?: T;
  warna?: T;
  urutan?: T;
  deskripsi?: T;
  kataKunci?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap_select".
 */
export interface RoadmapSelect<T extends boolean = true> {
  judul?: T;
  tahun?: T;
  tema?: T;
  jenis?: T;
  keterangan?: T;
  rencana?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "log-sinkron_select".
 */
export interface LogSinkronSelect<T extends boolean = true> {
  sumber?: T;
  status?: T;
  ringkasan?: T;
  ditambahkan?: T;
  diperbarui?: T;
  pesan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profil".
 */
export interface Profil {
  id: number;
  gelarDepan?: string | null;
  nama: string;
  gelarBelakang?: string | null;
  jabatan: string;
  /**
   * Contoh: 2024–2028
   */
  periode?: string | null;
  jurusan?: string | null;
  jabatanFungsional?: string | null;
  nip?: string | null;
  nidn?: string | null;
  bidang?: string | null;
  foto?: (number | null) | Media;
  /**
   * Kalimat utama di bagian atas. Bungkus satu frasa dengan *bintang* agar tampil miring sebagai aksen.
   */
  pernyataan: string;
  /**
   * Paragraf yang "terisi tinta" saat di-scroll
   */
  narasi?: string | null;
  /**
   * Catatan bahan ajar
   */
  bahanAjar?: string | null;
  sintaId?: string | null;
  scholarId?: string | null;
  profilFmipa?: string | null;
  email?: string | null;
  alamat?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Angka diperbarui otomatis tiap Senin 02.00 dari Google Scholar dan SINTA. Tekan tombol di bawah untuk memperbarui sekarang.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrik".
 */
export interface Metrik {
  id: number;
  scholar?: {
    sitasi?: number | null;
    hIndex?: number | null;
    i10?: number | null;
    entri?: number | null;
    diperbarui?: string | null;
  };
  scopus?: {
    artikel?: number | null;
    sitasi?: number | null;
    hIndex?: number | null;
  };
  sinta?: {
    skor?: number | null;
    skor3th?: number | null;
    diperbarui?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profil_select".
 */
export interface ProfilSelect<T extends boolean = true> {
  gelarDepan?: T;
  nama?: T;
  gelarBelakang?: T;
  jabatan?: T;
  periode?: T;
  jurusan?: T;
  jabatanFungsional?: T;
  nip?: T;
  nidn?: T;
  bidang?: T;
  foto?: T;
  pernyataan?: T;
  narasi?: T;
  bahanAjar?: T;
  sintaId?: T;
  scholarId?: T;
  profilFmipa?: T;
  email?: T;
  alamat?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "metrik_select".
 */
export interface MetrikSelect<T extends boolean = true> {
  scholar?:
    | T
    | {
        sitasi?: T;
        hIndex?: T;
        i10?: T;
        entri?: T;
        diperbarui?: T;
      };
  scopus?:
    | T
    | {
        artikel?: T;
        sitasi?: T;
        hIndex?: T;
      };
  sinta?:
    | T
    | {
        skor?: T;
        skor3th?: T;
        diperbarui?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSinkronMingguan".
 */
export interface TaskSinkronMingguan {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}